"""Initial migration

Revision ID: 7bd7c3570d25
Revises: 
Create Date: 2021-01-22 19:19:42.064574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd7c3570d25'
down_revision = None
branch_labels = None
depends_on = None

def data_upgrades():
    """Add any optional data upgrade migrations here!"""

    table = sa.sql.table('lab6_categories', sa.sql.column('name', sa.String))

    op.bulk_insert(table,
        [
            {'name': 'Программирование'},
            {'name': 'Математика'},
            {'name': 'Языкознание'},
        ]
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab6_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_lab6_categories_name'))
    )
    op.create_table('lab6_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('md5_hash', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(create_constraint=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_images')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_lab6_images_md5_hash'))
    )
    op.create_table('lab6_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_roles'))
    )
    op.create_table('lab6_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['lab6_roles.id'], name=op.f('fk_lab6_users_role_id_lab6_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_users')),
    sa.UniqueConstraint('login', name=op.f('uq_lab6_users_login'))
    )
    op.create_table('lab6_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=False),
    sa.Column('full_desc', sa.Text(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=True),
    sa.Column('rating_num', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('background_image_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['lab6_users.id'], name=op.f('fk_lab6_courses_author_id_lab6_users')),
    sa.ForeignKeyConstraint(['background_image_id'], ['lab6_images.id'], name=op.f('fk_lab6_courses_background_image_id_lab6_images')),
    sa.ForeignKeyConstraint(['category_id'], ['lab6_categories.id'], name=op.f('fk_lab6_courses_category_id_lab6_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_courses'))
    )
    op.create_table('lab6_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lab6_courses.id'], name=op.f('fk_lab6_reviews_course_id_lab6_courses')),
    sa.ForeignKeyConstraint(['user_id'], ['lab6_users.id'], name=op.f('fk_lab6_reviews_user_id_lab6_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_reviews'))
    )
    op.create_table('lab6_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lab6_courses.id'], name=op.f('fk_lab6_themes_course_id_lab6_courses')),
    sa.ForeignKeyConstraint(['parent_id'], ['lab6_themes.id'], name=op.f('fk_lab6_themes_parent_id_lab6_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_themes'))
    )
    op.create_table('lab6_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['lab6_themes.id'], name=op.f('fk_lab6_steps_theme_id_lab6_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_steps'))
    )
    op.create_table('lab6_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['lab6_steps.id'], name=op.f('fk_lab6_pages_step_id_lab6_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab6_pages')),
    sa.UniqueConstraint('step_id', name=op.f('uq_lab6_pages_step_id'))
    )
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab6_pages')
    op.drop_table('lab6_steps')
    op.drop_table('lab6_themes')
    op.drop_table('lab6_reviews')
    op.drop_table('lab6_courses')
    op.drop_table('lab6_users')
    op.drop_table('lab6_roles')
    op.drop_table('lab6_images')
    op.drop_table('lab6_categories')
    # ### end Alembic commands ###
